language: python
sudo: required
install: 
  - pip install -r requirements.txt
python:
  - "3.6"
script:
  - ./scripts/download_datasets Plaza2
  - ./scripts/run_important_notebooks
  - pytest test/
  - make html
