language: python
sudo: required
install: 
  - pip install -r requirements.txt
python:
  - "3.6"
script:
  - ./bin/download_datasets all
  - ./bin/run_important_notebooks
  - pytest test/
  - make html
